webapp/app/site/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired


class MessageForm(FlaskForm):
    text_area = TextAreaField('Message', render_kw={'rows': 10}, validators=[DataRequired()])
    submit = SubmitField('Submit text', id="msg-btn")

webapp/app/app.py
import os
from flask import Flask

from config import config_factory

from app.site import site as site_bp


def create_app(config_name=os.getenv('APP_ENV', 'default')):
    app = Flask(__name__)
    app.config.from_object(config_factory[config_name])

    app.register_blueprint(site_bp)

    return app

webapp/app/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__)

from . import routes

webapp/app/site/routes.py
import json
import requests

from flask import render_template, request, flash, redirect, url_for
import os

from app.site.forms import MessageForm
from . import site


@site.route("/", methods=['GET', 'POST'])
def home():
    form = MessageForm()
    msg_type = ''

    if form.validate_on_submit():
        msg = form.text_area.data
        api_url = os.getenv('API_URL')
        msg_json = json.dumps({'text': msg})

        try:
            resp = requests.post(api_url, msg_json)
            if resp.status_code == 200:
                msg_type = json.loads(resp.content).get('value')[0]
            else:
                flash('{} Error'.format(resp.status_code), 'error')
        except (requests.exceptions.MissingSchema, requests.exceptions.InvalidSchema):
            flash('API url should contain http(s)://.', 'error')
        except requests.exceptions.ConnectionError:
            flash('Could not establish connection with the API.', 'error')
        redirect(url_for('site.home', form=form, msg_type=msg_type))

    return render_template('index.html', form=form, msg_type=msg_type)


@site.route("/info")
def info():
    return render_template('info.html')


@site.route("/post", methods=["POST"])
def send_request():
    a=1

    r = request.form
    api_url = os.getenv('API_URL')
    req_data = list(request.form.keys())[0]

    try:
        resp = requests.post(api_url, req_data)
        if resp.status_code == 200:
            return resp.content
        else:
            print(resp.status_code)

    except Exception:
        return 'Cannot reach the api.'

    else:
        return 'error'

webapp/app/templates/index.html
{% extends "layout.html" %}

{% block head %}
    <script type="text/javascript" src="../static/js/site.js" defer></script>
{% endblock %}


{% block main_container %}
<h1 class="mt-5 pt-3">Check if the message is spam or ham</h1>
<p>Type some text and check if the message is spam or not.</p>
<div class="row">
        <form class="col btn-group-vertical" method="POST" action="{{ url_for('site.home') }}">
            {{ form.csrf_token }}

            {% with errors = get_flashed_messages(category_filter=["error"]) %}
                {% for error in errors %}
                    <div class="alert alert-warning" style="width:100%;">{{ error }}</div>
                {% endfor %}
            {% endwith %}

            {{ form.text_area(class_="form-control")}}
            {{ form.submit(class_="btn btn-block p-5 btn-light") }}
        </form>


<!--        <textarea id="msg-area" class="form-control" placeholder="Type your message here..." rows="10"></textarea>-->
<!--        <button type="button" class="btn btn-block p-5 btn-light"-->
<!--        id="msg-btn">Type your message</button>-->
</div>

<script type="text/javascript">
    var msg_type = "{{ msg_type }}";
</script>
{% endblock %}


webapp/app/templates/info.html
{% extends "layout.html" %}

{% block head %}
    <script type="text/javascript" src="../static/js/info.min.js" defer></script>
{% endblock %}


{% block main_container %}
<h1 class="mt-5 pt-3">Info</h1>
<p>Prediction model is trained on the SMS Spam Collection.
See more information about the dataset in the
<a href="https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection"
target="_blank">UCI Machine Learning Repository</a></p>
{% endblock %}


webapp/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Spam API</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  {% block head %}{% endblock %}
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container">
        <a href="{{ url_for('site.home') }}" class="navbar-brand">Spam API</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expand="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="{{ url_for('site.home') }}" class="nav-link" id="home-navlink">Home</a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('site.info') }}" class="nav-link" id="info-navlink">Info</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  </header>

  <!-- Main content -->
  <main role="main" class="container">
    {% block main_container %}
    {% endblock %}
  </main>

  <!-- <footer class="card-footer bg-light  footer-font-style text-muted footer-position"> -->
  <footer class="bg-light p-4 text-muted fixed-bottom text-center">
    <div class="container">
      <span class="text-muted">. . .</span>
    </div>
  </footer>

</body>
</html>


<!-- https://stackoverflow.com/questions/11178426/how-can-i-pass-data-from-flask-to-javascript-in-a-template -->